server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          host: ${HOSTNAME}
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
      - labels:
          container_name:
          stream:
      - regex:
          expression: '^(?P<message>.*)$'
      - output:
          source: message

  - job_name: app-access-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: app-access
          host: ${HOSTNAME}
          __path__: /var/log/laondry-order-service/access.log
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            method: method
            path: path
            query: query
            remote_ip: remote_ip
            ua: ua
            status: status
            duration_ms: duration_ms
            customer_id: customer_id
            outlet_id: outlet_id
            order_id: order_id
            order_no: order_no
      - labels:
          method:
          path:
          status:
          customer_id:
          outlet_id:
          order_id:
          order_no:
      - timestamp:
          source: ts
          format: RFC3339Nano
